### ISSUE TITLE
Icelandic language PR

### ISSUE THREAD

**Issue by HrafnPrescriby** [Bdaya-Dev/flutter_datetime_picker#5]
Would there be interest in receiving a PR which includes Icelandic language translations for this library?

My team has already implemented the minor changes needed and would like to contribute back.

**Edit**:
 In fact I see that there is already a pending PR https://github.com/Bdaya-Dev/flutter_datetime_picker/pull/1 with suggested changes. Will take a look at those.

**Comment by ahmednfwela** [comment]
I am down to merging any PR, just @ me when everything's ready for review :)

**Comment by HrafnPrescriby** [comment]
@ahmednfwela I believe the PR is good to go for merge.

**Comment by ahmednfwela** [comment]
merged, and will publish a new version soon
